from time import sleep

import os.path

_POSITIONS = os.path.join(os.path.dirname(os.getcwd()))  + '\\UNLIMITED_NINJA_BOT\settings\positions.ini'

class top_kages:
	def __init__(self, mouse, positions):
		self.mouse = mouse
		self.positions = positions
		
		self.mouse.move(self.positions.parse(_POSITIONS, 'functions', 'hover'))
		sleep(3)
		self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'open'))
		sleep(2)

	def practice(self, practice, ri):
		if ri == True:
			if practice == 'kazekage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
			elif practice == 'mizukage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
			elif practice == 'tsuchikage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
			elif practice == 'raikage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'raikage'))
				sleep(1)
			elif practice == 'hokage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'raikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'hokage'))
				sleep(1)
			elif practice == '4th_hokage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'raikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '4th_hokage'))
				sleep(1)
			elif practice == '1st_hokage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'raikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '4th_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '1st_hokage'))
				sleep(1)
			elif practice == '2nd_mizukage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'raikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '4th_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '1st_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mystical_shadow'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '2nd_tsuchikage'))
				sleep(1)
			elif practice == '6th_hokage':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'raikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '4th_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '1st_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mystical_shadow'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '2nd_tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '6th_hokage'))
				sleep(1)
			elif practice == 'all':
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'kazekage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mizukage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'raikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '4th_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '1st_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'mystical_shadow'))
				sleep(2)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '2nd_tsuchikage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '6th_hokage'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', '7th_hokage'))
				sleep(2)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'back'))
				sleep(1)
				self.mouse.move(self.positions.parse(_POSITIONS, 'top_kages', 'close'))
				sleep(1)
		else:
			pass